version: "3.7"

services:
  bobs-front:
    image: ghcr.io/wolf-361/bobs-duck:front-stable-lastest
    container_name: bobs-front
    restart: unless-stopped
    labels:   # Will be used by watchtower to update this container
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 127.0.0.1:9696:80
    depends_on:
      - bobs-back
      - bobs-db
  
  bobs-back:
    image: ghcr.io/wolf-361/bobs-duck:back-stable-lastest
    container_name: bobs-back
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 127.0.0.1:9697:3000
    depends_on:
      - bobs-db
    environment:
      # Mode
      MODE: 'prod'
      DB_LOGGING: 'false'

      # Database
      DB_HOST: 'bobs-db'
      DB_USER: 'bobs-db'
      DB_PASSWORD: '*@foWyYrMi9GVwZFb4GKdYRjkj.ZXC6j'

  bobs-db:
    image: postgres:16.0
    container_name: bobs-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'bobs-admin'
      POSTGRES_PASSWORD: '*@foWyYrMi9GVwZFb4GKdYRjkj.ZXC6j'
      POSTGRES_DB: 'bobs-db'

  bobs-watchtower:
    image: containrrr/watchtower
    container_name: bobs-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      WATCHTOWER_LABEL_ENABLE: 'true' # Only watch containers with the label com.centurylinklabs.watchtower.enable=truee
