version: "3.7"

services:
  # Pour en dev
  bobs-db:
    image: postgres:16.0
    container_name: bobs-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'bobs-admin'
      POSTGRES_PASSWORD: '*@foWyYrMi9GVwZFb4GKdYRjkj.ZXC6j'
      POSTGRES_DB: 'bobs-db'
